cc_library(
    name = "either",
    hdrs = [
        "left.h",
        "right.h",
        "ind_either.h",
        "either.h",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//:base"],
)
