cc_library(
    name = "nat",
    hdrs = [
        "add1.h",
        "equality.h",
        "ind_nat.h",
        "int32.h",
        "nat.h",
        "zero.h",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//:base"],
)
