cc_library(
    name = "var",
    hdrs = [
        "the.h",
        "typed_var.h",
        "var.h",
    ],
    visibility = [
        "//:__pkg__",
        "//lambda:__pkg__",
    ],
    deps = ["//:base"],
)
