cc_library(
    name = "lambda",
    hdrs = [
        "app.h",
        "lambda.h",
        "pi.h",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//:base",
        "//var",
    ],
)
